Repository adityaarakeri/super-scripts, pull requests merged in 2020-10, with the labels that each got.

#154 Tambola ticket generator
  README.md
  Tambola_Ticket_Generator/README.MD
  Tambola_Ticket_Generator/main.py
  Tambola_Ticket_Generator/requirements.txt
Labels: hacktoberfest-accepted

#166 Git change email
  README.md
  git_email_change/README.md
  git_email_change/git_email_change.py
Labels: hacktoberfest, hacktoberfest-accepted

#167 adding contributing guidelines
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#169 updating contributing guidelines
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#85 Adds Nasa Events API project
  nasa_events_api/Categories_ID.json
  nasa_events_api/README.md
  nasa_events_api/app.py
Labels: automerge

#88 Added a script to configure ubuntu terminal using zsh and oh_my_zsh.
  Terminal_configurator/Readme.md
  Terminal_configurator/terminal.sh
Labels: automerge

#74 Script to read a given excel file
  read_xl/File.xlsx
  read_xl/Pipfile.lock
  read_xl/read_xl.py
  read_xl/readme.md
Labels: automerge

#32 Add new automation script
  attendance_checker/Readme.md
  attendance_checker/auto_attend.py
  attendance_checker/images/Images/academic.png
  attendance_checker/images/Images/attend.png
  attendance_checker/images/Images/hi.png
  attendance_checker/images/Images/logout.png
  attendance_checker/images/Images/searchbar.png
  attendance_checker/images/Images/student.png
Labels: automerge

#187 Adding weather_logger script
  weather_logger/README.md
  weather_logger/database.xml
  weather_logger/requirements.txt
  weather_logger/weather_logger.py
Labels: automerge

#139 Added script for scheduled termination of computer(Apple)
  .DS_Store
  README.md
  scheduled_shutdown/.DS_Store
  scheduled_shutdown/README.md
  scheduled_shutdown/shutdown_computer.py
Labels: automerge

#132 Scripts for hook and hack to 10fastfinger website.
  auto_10fastfinger_jsscript/readme.md
  auto_10fastfinger_jsscript/src.js
  facebook_old_layout/readme.md
  facebook_old_layout/scr.js
Labels: automerge

#122 Add text to speech
  Text_to_speech/README.md
  Text_to_speech/abc.txt
  Text_to_speech/requirements.txt
  Text_to_speech/txtToSpeech.py
  Text_to_speech/voice.mp3
Labels: automerge

#127 added mysql dump script -- parth93QA
  mysql_dump_script/README.md
  mysql_dump_script/mysqlDump_linux.py
Labels: automerge

#46 Curl REST api for displaying the weather forecast in your shell
  README.md
  weather/README.md
  weather/forecast.sh
  weather/weather.png
Labels: automerge

#83 University courses
  get_university_courses/main.py
  get_university_courses/readme.md
Labels: automerge

#118 Added LinkedIn Followers Scraper
  linkedin_followes_scraper/README.md
  linkedin_followes_scraper/linkedin_followers_scraper.py
Labels: automerge

#117 Cartoonify Script
  Toonify/README.md
  Toonify/toonify-API-1.py
  Toonify/toonify-API-2.py
  Toonify/toonify-opencv.py
Labels: automerge

#43 Hacktoberfest 2019: Added to script to get emojis
  emoji/README.md
  emoji/emoji.sh
  emoji/emoji_list
Labels: automerge

#114 Reading Emails
  pythonGMailReader/pythonGMailReader.py
  pythonGMailReader/readme.txt
Labels: automerge

#45 Helper not to have to pass the default separator to Awk
  README.md
  tsv/README.md
  tsv/print_columns.sh
Labels: automerge

#115 Add a python script for converting a unix timestamp to human readable format
  unix_time_converter/README.md
  unix_time_converter/unix_time_converter.py
Labels: automerge

#37 add Insta_dp_downloader script
  insta_dp_downloader/README.md
  insta_dp_downloader/package-lock.json
  insta_dp_downloader/package.json
  insta_dp_downloader/script.js
Labels: automerge

#40 Add script to convert png to jpg image
  convert_png_to_jpg/README.md
  convert_png_to_jpg/convert.py
Labels: automerge

#194 Added Currency Exchange Rate
  currency_exchange_rate/Readme.md
  currency_exchange_rate/currency_exchange_rate.py
Labels: automerge

#190 Added Hash Compare Script for Powershell
  .vs/slnx.sqlite
  Powershell_Compare_Hashkeys/Compare_Hashkeys.ps1
  Powershell_Compare_Hashkeys/README.md
Labels: automerge

#113 Script: Go Binary Compiler
  README.md
  go_binary_compiler/README.md
  go_binary_compiler/cmd/helloworld/main.go
  go_binary_compiler/cmd/timenow/main.go
  go_binary_compiler/main.sh
Labels: automerge

#38 Add image to b64 encoder/decoder
  image_to_b64/Readme.md
  image_to_b64/convert.py
Labels: automerge

#198 clean up activity
  .gitignore
  .vs/slnx.sqlite
  README.md
  bash_script_generator
Labels: automerge, hacktoberfest, hacktoberfest-accepted

#199 updating readme and cleanup
  .DS_Store
  CONTRIBUTING.md
  README.md
Labels: automerge, hacktoberfest, hacktoberfest-accepted
